-- public."Departments" definition

-- Drop table

-- DROP TABLE public."Departments";

CREATE TABLE public."Departments" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"Name" varchar(100) NOT NULL,
	"Description" varchar(350) NULL,
	"IsActive" bool NOT NULL,
	"EntryDate" timestamptz NULL,
	"UpdatedDate" timestamptz NULL,
	CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);