-- public."Employees" definition

-- Drop table

-- DROP TABLE public."Employees";

CREATE TABLE public."Employees" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"EmployeeCode" varchar(8) NOT NULL,
	"Name" varchar(100) NOT NULL,
	"Salary" numeric NOT NULL,
	"DepartmentId" int4 NOT NULL,
	"Description" varchar(350) NULL,
	"IsActive" bool NOT NULL,
	"EntryDate" timestamptz NULL,
	"UpdatedDate" timestamptz NULL,
	CONSTRAINT "PK_Employees" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_Employees_DepartmentId" ON public."Employees" USING btree ("DepartmentId");
